CREATE TABLE "companies" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"symbol" text NOT NULL,
	"market_cap" numeric(20, 2) NOT NULL,
	"price" numeric(10, 2) NOT NULL,
	"daily_change" numeric(5, 2) NOT NULL,
	"daily_change_percent" numeric(5, 2) NOT NULL,
	"country" text NOT NULL,
	"country_code" text NOT NULL,
	"rank" integer NOT NULL,
	"logo_url" text,
	"industry" text,
	"sector" text,
	"website" text,
	"description" text,
	"ceo" text,
	"employees" integer,
	"pe_ratio" numeric(8, 2),
	"eps" numeric(8, 2),
	"beta" numeric(5, 3),
	"dividend_yield" numeric(5, 4),
	"volume" numeric(20, 2),
	"avg_volume" numeric(20, 2),
	"day_low" numeric(10, 2),
	"day_high" numeric(10, 2),
	"year_low" numeric(10, 2),
	"year_high" numeric(10, 2),
	"revenue" numeric(20, 0),
	"gross_profit" numeric(20, 0),
	"operating_income" numeric(20, 0),
	"net_income" numeric(20, 0),
	"total_assets" numeric(20, 0),
	"total_debt" numeric(20, 0),
	"cash_and_equivalents" numeric(20, 0),
	"return_3_year" numeric(8, 2),
	"return_5_year" numeric(8, 2),
	"return_10_year" numeric(8, 2),
	"max_drawdown_10_year" numeric(8, 2),
	"return_drawdown_ratio_10_year" numeric(8, 2),
	CONSTRAINT "companies_symbol_unique" UNIQUE("symbol")
);
--> statement-breakpoint
CREATE TABLE "ftse100_companies" (
	"id" serial PRIMARY KEY NOT NULL,
	"rank" integer NOT NULL,
	"symbol" varchar(10) NOT NULL,
	"name" varchar(200) NOT NULL,
	"market_cap" numeric(20, 2),
	"price" numeric(10, 2),
	"revenue" numeric(20, 2),
	"net_income" numeric(20, 2),
	"eps" numeric(10, 2),
	"pe_ratio" numeric(8, 2),
	"return_3_year" numeric(8, 4),
	"return_5_year" numeric(8, 4),
	"return_10_year" numeric(8, 4),
	"max_drawdown_3_year" numeric(8, 4),
	"max_drawdown_5_year" numeric(8, 4),
	"max_drawdown_10_year" numeric(8, 4),
	"return_drawdown_ratio_10_year" numeric(8, 4),
	"daily_change" numeric(10, 2),
	"daily_change_percent" numeric(8, 4),
	"sector" varchar(100),
	"industry" varchar(100),
	"country" varchar(2),
	"website" text,
	"description" text,
	"ceo" text,
	"employees" integer,
	"logo_url" text,
	"last_updated" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "ftse100_companies_symbol_unique" UNIQUE("symbol")
);
--> statement-breakpoint
CREATE TABLE "nasdaq100_companies" (
	"id" serial PRIMARY KEY NOT NULL,
	"rank" integer,
	"symbol" varchar(10) NOT NULL,
	"name" varchar(255) NOT NULL,
	"market_cap" numeric(15, 0),
	"price" numeric(10, 2),
	"daily_change" numeric(10, 2),
	"daily_change_percent" numeric(8, 4),
	"sector" varchar(100),
	"industry" varchar(100),
	"country" varchar(2),
	"website" text,
	"description" text,
	"ceo" text,
	"employees" integer,
	"logo_url" text,
	"pe_ratio" numeric(8, 2),
	"eps" numeric(8, 2),
	"beta" numeric(5, 3),
	"dividend_yield" numeric(5, 4),
	"revenue" numeric(15, 0),
	"net_income" numeric(15, 0),
	"total_debt" numeric(15, 0),
	"total_cash" numeric(15, 0),
	"free_cash_flow" numeric(15, 0),
	"return_3_year" numeric(8, 4),
	"return_5_year" numeric(8, 4),
	"return_10_year" numeric(8, 4),
	"max_drawdown_10_year" numeric(8, 4),
	"return_drawdown_ratio_10_year" numeric(8, 4),
	"last_updated" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "nasdaq100_companies_symbol_unique" UNIQUE("symbol")
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"sid" varchar PRIMARY KEY NOT NULL,
	"sess" jsonb NOT NULL,
	"expire" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" varchar,
	"first_name" varchar,
	"last_name" varchar,
	"profile_image_url" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "watchlist" (
	"id" serial PRIMARY KEY NOT NULL,
	"company_symbol" text NOT NULL,
	"user_id" varchar NOT NULL,
	"added_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "watchlist" ADD CONSTRAINT "watchlist_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "IDX_session_expire" ON "sessions" USING btree ("expire");