CREATE TABLE IF NOT EXISTS "dow_jones_companies" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"symbol" text NOT NULL,
	"market_cap" numeric(20, 2),
	"price" numeric(10, 2),
	"daily_change" numeric(10, 2),
	"daily_change_percent" numeric(5, 2),
	"country" text,
	"country_code" text,
	"rank" integer,
	"logo_url" text,
	"industry" text,
	"sector" text,
	"website" text,
	"description" text,
	"ceo" text,
	"employees" integer,
	"pe_ratio" numeric(10, 2),
	"eps" numeric(10, 2),
	"beta" numeric(8, 4),
	"dividend_yield" numeric(8, 4),
	"price_to_sales_ratio" numeric(10, 2),
	"net_profit_margin" numeric(8, 4),
	"volume" numeric(20, 0),
	"avg_volume" numeric(20, 0),
	"day_low" numeric(10, 2),
	"day_high" numeric(10, 2),
	"year_low" numeric(10, 2),
	"year_high" numeric(10, 2),
	"revenue" numeric(20, 0),
	"gross_profit" numeric(20, 0),
	"operating_income" numeric(20, 0),
	"net_income" numeric(20, 0),
	"total_assets" numeric(20, 0),
	"total_debt" numeric(20, 0),
	"cash_and_equivalents" numeric(20, 0),
	"return_3_year" numeric(8, 2),
	"return_5_year" numeric(8, 2),
	"return_10_year" numeric(8, 2),
	"max_drawdown_10_year" numeric(8, 2),
	"max_drawdown_5_year" numeric(8, 2),
	"max_drawdown_3_year" numeric(8, 2),
	"ar_mdd_ratio_10_year" numeric(10, 4),
	"ar_mdd_ratio_5_year" numeric(10, 4),
	"ar_mdd_ratio_3_year" numeric(10, 4),
	"revenue_growth_3y" numeric(8, 2),
	"revenue_growth_5y" numeric(8, 2),
	"revenue_growth_10y" numeric(8, 2),
	"free_cash_flow" numeric(20, 0),
	CONSTRAINT "dow_jones_companies_symbol_unique" UNIQUE("symbol")
);
ALTER TABLE "companies" ADD COLUMN "free_cash_flow" numeric(20, 0);
ALTER TABLE "nasdaq100_companies" ADD COLUMN "free_cash_flow" numeric(20, 0);
