-- Migration: Add revenue_y1..y10, fcf_y1..y10, and fcf_margin_median_10y columns
-- Run this in Supabase SQL Editor

-- Add columns to companies table
ALTER TABLE companies
ADD COLUMN IF NOT EXISTS revenue_y1 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y2 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y3 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y4 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y5 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y6 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y7 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y8 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y9 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y10 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y1 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y2 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y3 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y4 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y5 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y6 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y7 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y8 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y9 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y10 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_margin_median_10y NUMERIC(10, 4);

-- Add columns to sp500_companies table
ALTER TABLE sp500_companies
ADD COLUMN IF NOT EXISTS revenue_y1 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y2 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y3 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y4 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y5 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y6 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y7 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y8 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y9 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y10 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y1 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y2 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y3 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y4 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y5 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y6 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y7 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y8 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y9 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y10 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_margin_median_10y NUMERIC(10, 4);

-- Add columns to nasdaq100_companies table
ALTER TABLE nasdaq100_companies
ADD COLUMN IF NOT EXISTS revenue_y1 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y2 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y3 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y4 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y5 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y6 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y7 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y8 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y9 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y10 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y1 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y2 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y3 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y4 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y5 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y6 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y7 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y8 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y9 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y10 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_margin_median_10y NUMERIC(10, 4);

-- Add columns to dow_jones_companies table
ALTER TABLE dow_jones_companies
ADD COLUMN IF NOT EXISTS revenue_y1 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y2 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y3 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y4 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y5 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y6 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y7 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y8 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y9 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y10 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y1 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y2 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y3 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y4 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y5 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y6 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y7 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y8 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y9 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y10 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_margin_median_10y NUMERIC(10, 4);

-- Add columns to ftse100_companies table
ALTER TABLE ftse100_companies
ADD COLUMN IF NOT EXISTS revenue_y1 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y2 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y3 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y4 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y5 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y6 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y7 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y8 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y9 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS revenue_y10 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y1 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y2 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y3 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y4 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y5 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y6 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y7 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y8 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y9 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_y10 NUMERIC(20, 0),
ADD COLUMN IF NOT EXISTS fcf_margin_median_10y NUMERIC(10, 4);


