/**
 * Maps CompanyTable `sortBy` (camelCase API param) to Postgres column names
 * for index tables: sp500_companies, nasdaq100_companies, dow_jones_companies, ftse100_companies.
 * Unknown keys should fall back to a sensible default (e.g. market_cap) at the call site.
 */
export const INDEX_STOCK_SORT_MAP: Record<string, string> = {
  rank: "rank",
  name: "name",
  symbol: "symbol",
  marketCap: "market_cap",
  price: "price",
  dailyChange: "daily_change",
  dailyChangePercent: "daily_change_percent",
  country: "country",
  countryCode: "country_code",
  logoUrl: "logo_url",
  industry: "industry",
  sector: "sector",
  website: "website",
  description: "description",
  ceo: "ceo",
  employees: "employees",
  peRatio: "pe_ratio",
  eps: "eps",
  beta: "beta",
  dividendYield: "dividend_yield",
  volume: "volume",
  avgVolume: "avg_volume",
  dayLow: "day_low",
  dayHigh: "day_high",
  yearLow: "year_low",
  yearHigh: "year_high",
  revenue: "revenue",
  grossProfit: "gross_profit",
  operatingIncome: "operating_income",
  netIncome: "net_income",
  totalAssets: "total_assets",
  totalDebt: "total_debt",
  cashAndEquivalents: "cash_and_equivalents",
  return3Year: "return_3_year",
  return5Year: "return_5_year",
  return10Year: "return_10_year",
  maxDrawdown3Year: "max_drawdown_3_year",
  maxDrawdown5Year: "max_drawdown_5_year",
  maxDrawdown10Year: "max_drawdown_10_year",
  returnDrawdownRatio10Year: "return_drawdown_ratio_10_year",
  arMddRatio3Year: "ar_mdd_ratio_3_year",
  arMddRatio5Year: "ar_mdd_ratio_5_year",
  arMddRatio10Year: "ar_mdd_ratio_10_year",
  priceToSalesRatio: "price_to_sales_ratio",
  netProfitMargin: "net_profit_margin",
  revenueGrowth3Y: "revenue_growth_3y",
  revenueGrowth5Y: "revenue_growth_5y",
  revenueGrowth10Y: "revenue_growth_10y",
  freeCashFlow: "free_cash_flow",
  marginOfSafety: "margin_of_safety",
  dcfImpliedGrowth: "dcf_implied_growth",
  dcfEnterpriseValue: "dcf_enterprise_value",
  totalEquity: "total_equity",
  assetTurnover: "asset_turnover",
  financialLeverage: "financial_leverage",
  roe: "roe",
  roic: "roic",
  roic10YAvg: "roic_10y_avg",
  roic10YStd: "roic_10y_std",
  roicStability: "roic_stability",
  roicStabilityScore: "roic_stability_score",
  fcfMargin: "fcf_margin",
  fcfMarginMedian10Y: "fcf_margin_median_10y",
  debtToEquity: "debt_to_equity",
  interestCoverage: "interest_coverage",
  cashFlowToDebt: "cash_flow_to_debt",
  sharesOutstanding: "shares_outstanding",
};
