import { pgTable, varchar, bigint, unique, serial, text, numeric, integer, doublePrecision, index, jsonb, timestamp, foreignKey } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"




export const drizzleMigrations = pgTable("__drizzle_migrations", {
	hash: varchar({ length: 255 }).primaryKey().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdAt: bigint("created_at", { mode: "number" }),
});

export const dowJonesCompanies = pgTable("dow_jones_companies", {
	id: serial().primaryKey().notNull(),
	name: text().notNull(),
	symbol: text().notNull(),
	marketCap: numeric("market_cap", { precision: 20, scale:  2 }),
	price: numeric({ precision: 10, scale:  2 }),
	dailyChange: numeric("daily_change", { precision: 10, scale:  2 }),
	dailyChangePercent: numeric("daily_change_percent", { precision: 5, scale:  2 }),
	country: text(),
	countryCode: text("country_code"),
	rank: integer(),
	logoUrl: text("logo_url"),
	industry: text(),
	sector: text(),
	website: text(),
	description: text(),
	ceo: text(),
	employees: integer(),
	peRatio: numeric("pe_ratio", { precision: 10, scale:  2 }),
	eps: numeric({ precision: 10, scale:  2 }),
	beta: numeric({ precision: 8, scale:  4 }),
	dividendYield: numeric("dividend_yield", { precision: 8, scale:  4 }),
	priceToSalesRatio: numeric("price_to_sales_ratio", { precision: 10, scale:  2 }),
	netProfitMargin: numeric("net_profit_margin", { precision: 8, scale:  4 }),
	volume: numeric({ precision: 20, scale:  0 }),
	avgVolume: numeric("avg_volume", { precision: 20, scale:  0 }),
	dayLow: numeric("day_low", { precision: 10, scale:  2 }),
	dayHigh: numeric("day_high", { precision: 10, scale:  2 }),
	yearLow: numeric("year_low", { precision: 10, scale:  2 }),
	yearHigh: numeric("year_high", { precision: 10, scale:  2 }),
	revenue: numeric({ precision: 20, scale:  0 }),
	grossProfit: numeric("gross_profit", { precision: 20, scale:  0 }),
	operatingIncome: numeric("operating_income", { precision: 20, scale:  0 }),
	netIncome: numeric("net_income", { precision: 20, scale:  0 }),
	totalAssets: numeric("total_assets", { precision: 20, scale:  0 }),
	totalDebt: numeric("total_debt", { precision: 20, scale:  0 }),
	cashAndEquivalents: numeric("cash_and_equivalents", { precision: 20, scale:  0 }),
	return3Year: numeric("return_3_year", { precision: 8, scale:  2 }),
	return5Year: numeric("return_5_year", { precision: 8, scale:  2 }),
	return10Year: numeric("return_10_year", { precision: 8, scale:  2 }),
	maxDrawdown10Year: numeric("max_drawdown_10_year", { precision: 8, scale:  2 }),
	maxDrawdown5Year: numeric("max_drawdown_5_year", { precision: 8, scale:  2 }),
	maxDrawdown3Year: numeric("max_drawdown_3_year", { precision: 8, scale:  2 }),
	arMddRatio10Year: numeric("ar_mdd_ratio_10_year", { precision: 10, scale:  4 }),
	arMddRatio5Year: numeric("ar_mdd_ratio_5_year", { precision: 10, scale:  4 }),
	arMddRatio3Year: numeric("ar_mdd_ratio_3_year", { precision: 10, scale:  4 }),
	revenueGrowth3Y: numeric("revenue_growth_3y", { precision: 8, scale:  2 }),
	revenueGrowth5Y: numeric("revenue_growth_5y", { precision: 8, scale:  2 }),
	revenueGrowth10Y: numeric("revenue_growth_10y", { precision: 8, scale:  2 }),
	freeCashFlow: numeric("free_cash_flow", { precision: 20, scale:  0 }),
	marginOfSafety: numeric("margin_of_safety", { precision: 10, scale:  4 }),
	dcfImpliedGrowth: numeric("dcf_implied_growth", { precision: 10, scale:  4 }),
	dcfEnterpriseValue: numeric("dcf_enterprise_value", { precision: 20, scale:  0 }),
	totalEquity: numeric("total_equity", { precision: 20, scale:  0 }),
	assetTurnover: numeric("asset_turnover", { precision: 10, scale:  4 }),
	financialLeverage: numeric("financial_leverage", { precision: 10, scale:  4 }),
	dupontRoe: numeric("dupont_roe", { precision: 10, scale:  4 }),
	roe: numeric({ precision: 10, scale:  4 }),
	returnDrawdownRatio10Year: doublePrecision("return_drawdown_ratio_10_year"),
	latestFcf: numeric("latest_fcf", { precision: 20, scale:  0 }),
}, (table) => {
	return {
		dowJonesCompaniesSymbolUnique: unique("dow_jones_companies_symbol_unique").on(table.symbol),
	}
});

export const companies = pgTable("companies", {
	id: serial().primaryKey().notNull(),
	name: text().notNull(),
	symbol: text().notNull(),
	marketCap: numeric("market_cap", { precision: 20, scale:  2 }).notNull(),
	price: numeric({ precision: 10, scale:  2 }).notNull(),
	dailyChange: numeric("daily_change", { precision: 5, scale:  2 }),
	dailyChangePercent: numeric("daily_change_percent", { precision: 5, scale:  2 }),
	country: text().notNull(),
	countryCode: text("country_code"),
	rank: integer().notNull(),
	logoUrl: text("logo_url"),
	industry: text(),
	sector: text(),
	website: text(),
	description: text(),
	ceo: text(),
	employees: integer(),
	peRatio: numeric("pe_ratio", { precision: 8, scale:  2 }),
	eps: numeric({ precision: 8, scale:  2 }),
	beta: numeric({ precision: 5, scale:  3 }),
	dividendYield: numeric("dividend_yield", { precision: 8, scale:  4 }),
	volume: numeric({ precision: 20, scale:  2 }),
	avgVolume: numeric("avg_volume", { precision: 20, scale:  2 }),
	dayLow: numeric("day_low", { precision: 10, scale:  2 }),
	dayHigh: numeric("day_high", { precision: 10, scale:  2 }),
	yearLow: numeric("year_low", { precision: 10, scale:  2 }),
	yearHigh: numeric("year_high", { precision: 10, scale:  2 }),
	revenue: numeric({ precision: 20, scale:  0 }),
	grossProfit: numeric("gross_profit", { precision: 20, scale:  0 }),
	operatingIncome: numeric("operating_income", { precision: 20, scale:  0 }),
	netIncome: numeric("net_income", { precision: 20, scale:  0 }),
	totalAssets: numeric("total_assets", { precision: 20, scale:  0 }),
	totalDebt: numeric("total_debt", { precision: 20, scale:  0 }),
	cashAndEquivalents: numeric("cash_and_equivalents", { precision: 20, scale:  0 }),
	return3Year: numeric("return_3_year", { precision: 8, scale:  2 }),
	return5Year: numeric("return_5_year", { precision: 8, scale:  2 }),
	return10Year: numeric("return_10_year", { precision: 8, scale:  2 }),
	maxDrawdown10Year: numeric("max_drawdown_10_year", { precision: 8, scale:  2 }),
	returnDrawdownRatio10Year: numeric("return_drawdown_ratio_10_year", { precision: 8, scale:  2 }),
	arMddRatio10Year: numeric("ar_mdd_ratio_10_year", { precision: 10, scale:  4 }),
	maxDrawdown5Year: numeric("max_drawdown_5_year", { precision: 8, scale:  2 }),
	maxDrawdown3Year: numeric("max_drawdown_3_year", { precision: 8, scale:  2 }),
	arMddRatio5Year: numeric("ar_mdd_ratio_5_year", { precision: 10, scale:  4 }),
	arMddRatio3Year: numeric("ar_mdd_ratio_3_year", { precision: 10, scale:  4 }),
	priceToSalesRatio: numeric("price_to_sales_ratio", { precision: 8, scale:  2 }),
	netProfitMargin: numeric("net_profit_margin", { precision: 8, scale:  4 }),
	returnOnEquity: numeric("return_on_equity", { precision: 8, scale:  4 }),
	returnOnAssets: numeric("return_on_assets", { precision: 8, scale:  4 }),
	debtToEquity: numeric("debt_to_equity", { precision: 8, scale:  4 }),
	revenueGrowth3Y: numeric("revenue_growth_3y", { precision: 8, scale:  2 }),
	revenueGrowth5Y: numeric("revenue_growth_5y", { precision: 8, scale:  2 }),
	revenueGrowth10Y: numeric("revenue_growth_10y", { precision: 8, scale:  2 }),
	freeCashFlow: numeric("free_cash_flow", { precision: 20, scale:  0 }),
	marginOfSafety: numeric("margin_of_safety", { precision: 10, scale:  4 }),
	dcfImpliedGrowth: numeric("dcf_implied_growth", { precision: 10, scale:  4 }),
	dcfEnterpriseValue: numeric("dcf_enterprise_value", { precision: 20, scale:  0 }),
	totalEquity: numeric("total_equity", { precision: 20, scale:  0 }),
	assetTurnover: numeric("asset_turnover", { precision: 10, scale:  4 }),
	financialLeverage: numeric("financial_leverage", { precision: 10, scale:  4 }),
	dupontRoe: numeric("dupont_roe", { precision: 10, scale:  4 }),
	roe: numeric({ precision: 10, scale:  4 }),
}, (table) => {
	return {
		companiesSymbolUnique: unique("companies_symbol_unique").on(table.symbol),
	}
});

export const sessions = pgTable("sessions", {
	sid: varchar().primaryKey().notNull(),
	sess: jsonb().notNull(),
	expire: timestamp({ mode: 'string' }).notNull(),
}, (table) => {
	return {
		iDxSessionExpire: index("IDX_session_expire").on(table.expire),
	}
});

export const watchlist = pgTable("watchlist", {
	id: serial().primaryKey().notNull(),
	companySymbol: text("company_symbol").notNull(),
	userId: varchar("user_id").notNull().references(() => users.id, { onDelete: "cascade" } ),
	addedAt: timestamp("added_at", { mode: 'string' }).defaultNow(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => {
	return {
		watchlistUserCompanyUnique: unique("watchlist_user_company_unique").on(table.companySymbol, table.userId),
	}
});

export const users = pgTable("users", {
	id: varchar().primaryKey().notNull(),
	email: varchar(),
	firstName: varchar("first_name"),
	lastName: varchar("last_name"),
	profileImageUrl: varchar("profile_image_url"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
	subscriptionTier: varchar("subscription_tier", { length: 255 }).default('free').notNull(),
	stripeCustomerId: varchar("stripe_customer_id"),
	stripeSubscriptionId: varchar("stripe_subscription_id"),
}, (table) => {
	return {
		usersEmailUnique: unique("users_email_unique").on(table.email),
	}
});

export const nasdaq100Companies = pgTable("nasdaq100_companies", {
	id: serial().primaryKey().notNull(),
	name: text().notNull(),
	symbol: text().notNull(),
	marketCap: numeric("market_cap", { precision: 20, scale:  2 }),
	price: numeric({ precision: 10, scale:  2 }),
	dailyChange: numeric("daily_change", { precision: 5, scale:  2 }),
	dailyChangePercent: numeric("daily_change_percent", { precision: 5, scale:  2 }),
	country: text(),
	countryCode: text("country_code"),
	rank: integer(),
	logoUrl: text("logo_url"),
	industry: text(),
	sector: text(),
	website: text(),
	description: text(),
	ceo: text(),
	employees: integer(),
	peRatio: numeric("pe_ratio", { precision: 8, scale:  2 }),
	eps: numeric({ precision: 8, scale:  2 }),
	beta: numeric({ precision: 5, scale:  3 }),
	dividendYield: numeric("dividend_yield", { precision: 8, scale:  4 }),
	volume: numeric({ precision: 20, scale:  2 }),
	avgVolume: numeric("avg_volume", { precision: 20, scale:  2 }),
	dayLow: numeric("day_low", { precision: 10, scale:  2 }),
	dayHigh: numeric("day_high", { precision: 10, scale:  2 }),
	yearLow: numeric("year_low", { precision: 10, scale:  2 }),
	yearHigh: numeric("year_high", { precision: 10, scale:  2 }),
	revenue: numeric({ precision: 20, scale:  0 }),
	grossProfit: numeric("gross_profit", { precision: 20, scale:  0 }),
	operatingIncome: numeric("operating_income", { precision: 20, scale:  0 }),
	netIncome: numeric("net_income", { precision: 20, scale:  0 }),
	totalAssets: numeric("total_assets", { precision: 20, scale:  0 }),
	totalDebt: numeric("total_debt", { precision: 20, scale:  0 }),
	cashAndEquivalents: numeric("cash_and_equivalents", { precision: 20, scale:  0 }),
	return3Year: numeric("return_3_year", { precision: 8, scale:  2 }),
	return5Year: numeric("return_5_year", { precision: 8, scale:  2 }),
	return10Year: numeric("return_10_year", { precision: 8, scale:  2 }),
	maxDrawdown10Year: numeric("max_drawdown_10_year", { precision: 8, scale:  2 }),
	maxDrawdown5Year: numeric("max_drawdown_5_year", { precision: 8, scale:  2 }),
	maxDrawdown3Year: numeric("max_drawdown_3_year", { precision: 8, scale:  2 }),
	returnDrawdownRatio10Year: numeric("return_drawdown_ratio_10_year", { precision: 8, scale:  2 }),
	arMddRatio10Year: numeric("ar_mdd_ratio_10_year", { precision: 10, scale:  4 }),
	arMddRatio5Year: numeric("ar_mdd_ratio_5_year", { precision: 10, scale:  4 }),
	arMddRatio3Year: numeric("ar_mdd_ratio_3_year", { precision: 10, scale:  4 }),
	priceToSalesRatio: numeric("price_to_sales_ratio", { precision: 8, scale:  2 }),
	netProfitMargin: numeric("net_profit_margin", { precision: 8, scale:  4 }),
	returnOnEquity: numeric("return_on_equity", { precision: 8, scale:  4 }),
	returnOnAssets: numeric("return_on_assets", { precision: 8, scale:  4 }),
	debtToEquity: numeric("debt_to_equity", { precision: 8, scale:  4 }),
	revenueGrowth3Y: numeric("revenue_growth_3y", { precision: 8, scale:  2 }),
	revenueGrowth5Y: numeric("revenue_growth_5y", { precision: 8, scale:  2 }),
	revenueGrowth10Y: numeric("revenue_growth_10y", { precision: 8, scale:  2 }),
	freeCashFlow: numeric("free_cash_flow", { precision: 20, scale:  0 }),
	marginOfSafety: numeric("margin_of_safety", { precision: 10, scale:  4 }),
	dcfImpliedGrowth: numeric("dcf_implied_growth", { precision: 10, scale:  4 }),
	dcfEnterpriseValue: numeric("dcf_enterprise_value", { precision: 20, scale:  0 }),
	totalEquity: numeric("total_equity", { precision: 20, scale:  0 }),
	assetTurnover: numeric("asset_turnover", { precision: 10, scale:  4 }),
	financialLeverage: numeric("financial_leverage", { precision: 10, scale:  4 }),
	dupontRoe: numeric("dupont_roe", { precision: 10, scale:  4 }),
	roe: numeric({ precision: 10, scale:  4 }),
	latestFcf: numeric("latest_fcf", { precision: 20, scale:  0 }),
}, (table) => {
	return {
		nasdaq100CompaniesSymbolUnique: unique("nasdaq100_companies_symbol_unique").on(table.symbol),
	}
});

export const sp500Companies = pgTable("sp500_companies", {
	id: serial().primaryKey().notNull(),
	name: text().notNull(),
	symbol: text().notNull(),
	marketCap: numeric("market_cap", { precision: 20, scale:  2 }),
	price: numeric({ precision: 10, scale:  2 }),
	dailyChange: numeric("daily_change", { precision: 5, scale:  2 }),
	dailyChangePercent: numeric("daily_change_percent", { precision: 5, scale:  2 }),
	country: text(),
	countryCode: text("country_code"),
	rank: integer(),
	logoUrl: text("logo_url"),
	industry: text(),
	sector: text(),
	website: text(),
	description: text(),
	ceo: text(),
	employees: integer(),
	peRatio: numeric("pe_ratio", { precision: 8, scale:  2 }),
	eps: numeric({ precision: 8, scale:  2 }),
	beta: numeric({ precision: 5, scale:  3 }),
	dividendYield: numeric("dividend_yield", { precision: 8, scale:  4 }),
	volume: numeric({ precision: 20, scale:  2 }),
	avgVolume: numeric("avg_volume", { precision: 20, scale:  2 }),
	dayLow: numeric("day_low", { precision: 10, scale:  2 }),
	dayHigh: numeric("day_high", { precision: 10, scale:  2 }),
	yearLow: numeric("year_low", { precision: 10, scale:  2 }),
	yearHigh: numeric("year_high", { precision: 10, scale:  2 }),
	revenue: numeric({ precision: 20, scale:  0 }),
	grossProfit: numeric("gross_profit", { precision: 20, scale:  0 }),
	operatingIncome: numeric("operating_income", { precision: 20, scale:  0 }),
	netIncome: numeric("net_income", { precision: 20, scale:  0 }),
	totalAssets: numeric("total_assets", { precision: 20, scale:  0 }),
	totalDebt: numeric("total_debt", { precision: 20, scale:  0 }),
	cashAndEquivalents: numeric("cash_and_equivalents", { precision: 20, scale:  0 }),
	return3Year: numeric("return_3_year", { precision: 8, scale:  2 }),
	return5Year: numeric("return_5_year", { precision: 8, scale:  2 }),
	return10Year: numeric("return_10_year", { precision: 8, scale:  2 }),
	maxDrawdown10Year: numeric("max_drawdown_10_year", { precision: 8, scale:  2 }),
	maxDrawdown5Year: numeric("max_drawdown_5_year", { precision: 8, scale:  2 }),
	maxDrawdown3Year: numeric("max_drawdown_3_year", { precision: 8, scale:  2 }),
	returnDrawdownRatio10Year: numeric("return_drawdown_ratio_10_year", { precision: 8, scale:  2 }),
	arMddRatio10Year: numeric("ar_mdd_ratio_10_year", { precision: 10, scale:  4 }),
	arMddRatio5Year: numeric("ar_mdd_ratio_5_year", { precision: 10, scale:  4 }),
	arMddRatio3Year: numeric("ar_mdd_ratio_3_year", { precision: 10, scale:  4 }),
	priceToSalesRatio: numeric("price_to_sales_ratio", { precision: 8, scale:  2 }),
	netProfitMargin: numeric("net_profit_margin", { precision: 8, scale:  4 }),
	returnOnEquity: numeric("return_on_equity", { precision: 8, scale:  4 }),
	returnOnAssets: numeric("return_on_assets", { precision: 8, scale:  4 }),
	debtToEquity: numeric("debt_to_equity", { precision: 8, scale:  4 }),
	revenueGrowth3Y: numeric("revenue_growth_3y", { precision: 8, scale:  2 }),
	revenueGrowth5Y: numeric("revenue_growth_5y", { precision: 8, scale:  2 }),
	revenueGrowth10Y: numeric("revenue_growth_10y", { precision: 8, scale:  2 }),
	freeCashFlow: numeric("free_cash_flow", { precision: 20, scale:  0 }),
	marginOfSafety: numeric("margin_of_safety", { precision: 10, scale:  4 }),
	dcfImpliedGrowth: numeric("dcf_implied_growth", { precision: 10, scale:  4 }),
	dcfEnterpriseValue: numeric("dcf_enterprise_value", { precision: 20, scale:  0 }),
	totalEquity: numeric("total_equity", { precision: 20, scale:  0 }),
	assetTurnover: numeric("asset_turnover", { precision: 10, scale:  4 }),
	financialLeverage: numeric("financial_leverage", { precision: 10, scale:  4 }),
	dupontRoe: numeric("dupont_roe", { precision: 10, scale:  4 }),
	roe: numeric({ precision: 10, scale:  4 }),
	latestFcf: numeric("latest_fcf", { precision: 20, scale:  0 }),
}, (table) => {
	return {
		sp500CompaniesSymbolUnique: unique("sp500_companies_symbol_unique").on(table.symbol),
	}
});
